[package]
name = "advent_of_code"
version = "0.1.0"
authors = ["Bruce Armstrong <bruce@fortressofgeekdom.org>"]

[lib]
bench = false

[dependencies]
aoc-runner = "^0.3"
aoc-runner-derive = "^0.3"
nom = "5.1.2"

[profile.release]
debug = true