/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.fortressofgeekdom.kotlin-application-conventions")
}

dependencies {
    implementation(project(":utilities"))
}

application {
    // Define the main class for the application.
    mainClass.set("org.fortressofgeekdom.aoc.AppKt")
}
